name: Publish Master Branch
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'react-boilerplate-2020-docker' #Must be unique in Heroku
          heroku_email: 'leslie.alldridge@gmail.com'
          buildpack: 'mars/create-react-app' #OPTIONAL
          usedocker: true
